config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resources :favorites, only: [:index ,:create, :destroy]
    get "follow_list" => "users#follow_list"
    get "follower_list" => "users#follower_list"
  end
  resources :relationships, only: [:create, :destroy]
  resources :impressions, only: [:index, :show, :create, :destroy] do
    resources :post_impressions, only: [:create, :destroy]
  end
  get "search_content" => "impressions#search_content"
  get "search" => "searches#search"
  post 'favorite/:id' => 'favorites#create', as: 'create_favorite'
  delete 'favorite/:id' => 'favorites#destroy',as: 'destroy_favorite'
  root to: 'impressions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/impression.rb
class Impression < ApplicationRecord
  has_many :content_relations, dependent: :destroy
  has_many :contents, through: :content_relations
  belongs_to :user
  has_many :post_impressions, dependent: :destroy
  has_many :favorites, dependent: :destroy
  validates :body, presence: true, length: { maximum: 200 }
  def self.looks(search, word)
    if search == "perfect_match"
      @impression = Impression.where("body LIKE?","#{word}")
    elsif search == "partial_match"
      @impression = Impression.where("body LIKE?","%#{word}%")
    else
      @impression = Impression.all
    end
  end
  def save_content(sent_contents)
    current_contents = self.contents.pluck(:name) unless self.contents.nil?
    old_contents = current_contents - sent_contents
    new_contents = sent_contents - current_contents
    old_contents.each do |old|
      self.contents.delete Content.find_by(name: old)
    end
    new_contents.each do |new|
      new_impression_content = Content.find_or_create_by(name: new)
      self.contents << new_impression_content
    end
  end
end

app/controllers/impressions_controller.rb
class ImpressionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search_content]
  def index
    @new_impression = Impression.new
    @impressions = Impression.page(params[:page]).per(5)
    @content_list = Content.all
    @content = Content.all
  end
  def show
    @new_impression = Impression.new
    @impression = Impression.find(params[:id])
    @impression_contents = @impression.contents
    @post_impressions = @impression.post_impressions.page(params[:page]).per(5)
    @post_impression = PostImpression.new
    @content = Content.all
  end
  def search_content
    @content_list = Content.all
    @content = Content.find(params[:content_id])
    @impressions = @content.impressions
  end
  def create
    @new_impression = Impression.new(impression_params)
    @new_impression.user_id = current_user.id
    content_list = params[:impression][:name].split('　')
    if @new_impression.save
       @new_impression.save_content(content_list)
       flash[:success] = '投稿が完了しました'
       redirect_to root_path
    else
       flash[:alert] = '投稿が失敗しました'
       redirect_back fallback_location: root_path
    end
  end
  def destroy
    @impression = Impression.find(params[:id])
    @impression.destroy
    flash[:success] = '投稿を削除しました'
    redirect_back fallback_location: root_path
  end
  private
  def impression_params
    params.require(:impression).permit(:body, :user_id)
  end
end

app/helpers/impressions_helper.rb
module ImpressionsHelper
end

app/views/impressions/index.html.erb
<%= flash[:alert] %>
<%= flash[:success] %>
<div class = 'body'>
 <% if user_signed_in? %>
 <div class = 'new-impression'>
  <h5>思いの丈をぶちまけよう！</h5>
   <div class="impression-field">
    <%= form_with model:@new_impression, url: impressions_path ,local: true do |f| %>
     <h3>感想(200文字まで)</h3>
      <%= f.text_field :body %>
      <%= f.hidden_field :user_id, value: current_user.id %>

   <div class="tag-field">
    <h3>タグ</h3><h5>(複数タグをつける際はタグの間を全角スペースで区切ってください)</h5>
     <%= f.text_field :name %>
　   <%= f.submit "投稿" %>
　 </div>

    <% end %>
  </div>
   <div class = "seach">
      <h3>検索窓</h3>
      <%= form_with url: search_path, local: true, method: :get do |f| %>
        <%= f.text_field :word %></br>
        <%= f.select :range, options_for_select([['ユーザー','User'],  ['タグ','Content'],  ['投稿','Impression']]) %></br>
        <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
        <%= f.submit "検索" %>
      <% end %>
   </div>
   <div class = "tag-list">
    <h3>タグ一覧</h3>
     <% @content.each do |content| %>
      <%= link_to content.name, search_content_path(content_id: content.id) %>
      <%="(#{content.impressions.count})" %></br>
     <% end %>
   </div>
 </div>
 <% else %>

 <div class = 'new-impression'>
  <div class = "seach">
      <h3>検索窓</h3>
      <%= form_with url: search_path, local: true, method: :get do |f| %>
        <%= f.text_field :word %></br>
        <%= f.select :range, options_for_select([['ユーザー','User'],  ['タグ','Content'],  ['投稿','Impression']]) %></br>
        <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
        <%= f.submit "検索" %>
      <% end %>
   </div>
   <div class = "tag-list">
    <h3>タグ一覧</h3>
     <% @content.each do |content| %>
      <%= link_to content.name, search_content_path(content_id: content.id) %>
      <%="(#{content.impressions.count})" %></br>
     <% end %>
   </div>
 </div>
 <% end %>
 <% if user_signed_in? %>
 <div class = 'impression-body'>
   <% @impressions.each do |impression| %>
    <div class = 'impression-list'>
     <div class = "impression-list-head">
      <div class ="impression-list-icon">
       <%= attachment_image_tag impression.user, :image , fallback: "no-image.png", :size => '60x50' %>
      </div>
      <div class ="impression-list-body-name">
       <%= link_to impression.user.name, user_path(impression.user_id) %></br>
      </div>
      <div id="favorite_buttons_<%= impression.id %>">
        <%= render "favorites/favorite",impression: impression %>
      </div>
     </div>
     <div class ="impression-list-body">
      <%= link_to impression.body, impression_path(impression) %></br>
      <%= impression.created_at.strftime('%Y/%m/%d') %></br>
      <% impression.contents.each do |content| %>
       <%= link_to content.name, search_content_path(content_id: content.id) %>
      <% end %></br>

     </div>
     <div class = "impression-list-link">
       <%= link_to 'コメント一覧へ',impression_path(impression) %><a>(<%= impression.post_impressions.count %>)</a>
       <% if current_user.id == impression.user_id %>
        <%= link_to '削除', impression_path(impression),method: :delete, data: { confirm: '本当にいいですか?' } %>
       <% end %>
     </div>
    </div>
   <% end %>
 <% else %>
 <div class = 'impression-body'>
   <% @impressions.each do |impression| %>
    <div class = 'impression-list'>
     <div class = "impression-list-head">
      <div class ="impression-list-icon">
       <%= attachment_image_tag impression.user, :image , fallback: "no-image.png", :size => '60x50' %>
      </div>
      <div class ="impression-list-body-name">
       <%= link_to impression.user.name, user_path(impression.user_id) %></br>
      </div>
     </div>
     <div class ="impression-list-body">
      <%= impression.body %></br>
      <%= impression.created_at.strftime('%Y/%m/%d') %></br>
      <% impression.contents.each do |content| %>
       <%= link_to content.name, search_content_path(content_id: content.id) %>
      <% end %></br>

     </div>
     <div class = "impression-list-link">
       <%= link_to 'コメント一覧へ',impression_path(impression) %><a>(<%= impression.post_impressions.count %>)</a>
       <% if user_signed_in? %>
        <% if current_user.id == impression.user_id %>
         <%= link_to '削除', impression_path(impression),method: :delete, data: { confirm: '本当にいいですか?' } %>
        <% else %>
        <% end %>
       <% else %>
       <% end %>
     </div>
   </div>
   <% end %>
 <% end %>
  <%= paginate @impressions %>
  </div>
 </div>

app/views/impressions/search_content.html.erb
<%= flash[:alert] %>
<%= flash[:success] %>
<div class = 'body'>
 <div class = 'new-impression'>
    <div class = "seach">
      <h3>検索窓</h3>
      <%= form_with url: search_path, local: true, method: :get do |f| %>
        <%= f.text_field :word %></br>
        <%= f.select :range, options_for_select([['ユーザー','User'],  ['タグ','Content'],  ['投稿','Impression']]) %><br>
        <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
        <%= f.submit "検索" %>
      <% end %>
   </div>
 <div class = "tag-list">
   <h3>タグ一覧</h3>
   <% @content_list.each do |list|%>
    <%=link_to list.name,search_content_path(content_id: list.id) %>
    <%="(#{list.impressions.count})" %><br>
   <% end %>
 </div>
 </div>

<% if user_signed_in? %>
 <div class = 'impression-body'>
   <h3>タグが<%=@content.name%>の投稿一覧</h3>
   <% @impressions.each do |impression| %>
    <div class = 'impression-list'>
     <div class = "impression-list-head">
      <div class ="impression-list-icon">
       <%= attachment_image_tag impression.user, :image , fallback: "no-image.png", :size => '60x50' %>
      </div>
      <div class ="impression-list-body-name">
       <%= link_to impression.user.name, user_path(impression.user_id) %><br>
      </div>
      <div id="favorite_buttons_<%= impression.id %>">
        <%= render "favorites/favorite",impression: impression %>
      </div>
     </div>
     <div class ="impression-list-body">
      <%= link_to impression.body, impression_path(impression) %><br>
      <%= impression.created_at.strftime('%Y/%m/%d') %><br>
      <% impression.contents.each do |content| %>
       <%= link_to content.name, search_content_path(content_id: content.id) %>
      <% end %><br>

     </div>
     <div class = "impression-list-link">
       <%= link_to 'コメント一覧へ',impression_path(impression) %><a>(<%= impression.post_impressions.count %>)</a>
       <% if current_user.id == impression.user_id %>
        <%= link_to '削除', impression_path(impression),method: :delete, data: { confirm: '本当にいいですか?' } %>
       <% end %>
     </div>
    </div>
   <% end %>
 <% else %>
 <div class = 'impression-body'>
   <h3>タグが<%=@content.name%>の投稿一覧</h3>
   <% @impressions.each do |impression| %>
    <div class = 'impression-list'>
     <div class = "impression-list-head">
      <div class ="impression-list-icon">
       <%= attachment_image_tag impression.user, :image , fallback: "no-image.png", :size => '60x50' %>
      </div>
      <div class ="impression-list-body-name">
       <%= link_to impression.user.name, user_path(impression.user_id) %><br>
      </div>
     </div>
     <div class ="impression-list-body">
      <%= impression.body %><br>
      <%= impression.created_at.strftime('%Y/%m/%d') %><br>
      <% impression.contents.each do |content| %>
       <%= link_to content.name, search_content_path(content_id: content.id) %>
      <% end %><br>

     </div>
     <div class = "impression-list-link">
       <%= link_to 'コメント一覧へ',impression_path(impression) %><a>(<%= impression.post_impressions.count %>)</a>
       <% if user_signed_in? %>
        <% if current_user.id == impression.user_id %>
         <%= link_to '削除', impression_path(impression),method: :delete, data: { confirm: '本当にいいですか?' } %>
        <% else %>
        <% end %>
       <% else %>
       <% end %>
     </div>
   </div>
   <% end %>
 <% end %>
</div>

app/views/impressions/show.html.erb
<%= flash[:alert] %>
<%= flash[:success] %>
<div class = 'body'>
 <% if user_signed_in? %>
 <div class = 'new-impression'>
  <h5>思いの丈をぶちまけよう！</h5>
   <div class="impression-field">
    <%= form_with model:@new_impression, url: impressions_path ,local: true do |f| %>
     <h3>感想</h3>
      <%= f.text_field :body %>
      <%= f.hidden_field :user_id, value: current_user.id %>

   <div class="tag-field">
    <h3>タグ</h3><h5>(複数タグをつける際はタグの間を全角スペースで区切ってください)</h5>
     <%= f.text_field :name %>
　   <%= f.submit "投稿" %>
　 </div>

    <% end %>
  </div>
  <div class = "seach">
      <h3>検索窓</h3>
      <%= form_with url: search_path, local: true, method: :get do |f| %>
        <%= f.text_field :word %></br>
        <%= f.select :range, options_for_select([['ユーザー','User'],  ['タグ','Content'],  ['投稿','Impression']]) %><br>
        <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
        <%= f.submit "検索" %>
      <% end %>
   </div>
   <div class = "tag-list">
    <h3>タグ一覧</h3>
     <% @content.each do |content| %>
      <%= link_to content.name, search_content_path(content_id: content.id) %>
      <%="(#{content.impressions.count})" %><br>
     <% end %>
   </div>
 </div>
 <% else %>
 <div class = 'new-impression'>
  <div class = "seach">
      <h3>検索窓</h3>
      <%= form_with url: search_path, local: true, method: :get do |f| %>
        <%= f.text_field :word %></br>
        <%= f.select :range, options_for_select([['ユーザー','User'],  ['タグ','Content'],  ['投稿','Impression']]) %><br>
        <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
        <%= f.submit "検索" %>
      <% end %>
   </div>
   <div class = "tag-list">
    <h3>タグ一覧</h3>
     <% @content.each do |content| %>
      <%= link_to content.name, search_content_path(content_id: content.id) %>
      <%="(#{content.impressions.count})" %><br>
     <% end %>
   </div>
 </div>
 <% end %>
<div class = 'impression-body'>
 <% if user_signed_in? %>
  <div class = 'impression-list'>
     <div class = "impression-list-head">
      <div class ="impression-list-icon">
       <%= attachment_image_tag @impression.user, :image , fallback: "no-image.png", :size => '60x50' %>
      </div>
      <div class ="impression-list-body-name">
       <%= link_to @impression.user.name, user_path(@impression.user_id) %><br>
      </div>
      <div id="favorite_buttons_<%= @impression.id %>">
        <%= render "favorites/favorite",impression: @impression %>
      </div>
     </div>
     <div class ="impression-list-body">
      <%= link_to @impression.body, impression_path(@impression) %><br>
      <%= @impression.created_at.strftime('%Y/%m/%d') %><br>
      <% @impression.contents.each do |content| %>
       <%= link_to content.name, search_content_path(content_id: content.id) %>
      <% end %><br>

     </div>
     <div class = "impression-list-link">
       <% if current_user.id == @impression.user_id %>
        <%= link_to '削除', impression_path(@impression),method: :delete, data: { confirm: '本当にいいですか?' } %>
       <% end %>
     </div>
 </div>
 <% else %>
   <div class = 'impression-list'>
     <div class = "impression-list-head">
      <div class ="impression-list-icon">
       <%= attachment_image_tag @impression.user, :image , fallback: "no-image.png", :size => '60x50' %>
      </div>
      <div class ="impression-list-body-name">
       <%= link_to @impression.user.name, user_path(@impression.user_id) %><br>
      </div>
     </div>
     <div class ="impression-list-body">
      <%= link_to @impression.body, impression_path(@impression) %><br>
      <%= @impression.created_at.strftime('%Y/%m/%d') %><br>
      <% @impression.contents.each do |content| %>
       <%= link_to content.name, search_content_path(content_id: content.id) %>
      <% end %><br>

     </div>
   </div>


<% end %>

  <div class = 'impression-detail-res'>
   <% if user_signed_in? %>
    <div>
      <%= form_with(model:[@impression, @post_impression], local: true) do |f| %>
     <div class="field">
      <h3><%= f.label :返信 %><br></h3>
      <%= f.text_field :body %><%= f.submit "コメントする" %>
　   </div>

      <% end %>
    </div>
   <% else %>
   <% end %>
    <% @post_impressions.each do |post_impression| %>
    <div>
     <%= link_to post_impression.user.name, user_path(post_impression.user_id) %><br>
     <%= post_impression.body %></br>
     <%= post_impression.created_at.strftime('%Y/%m/%d') %><br>
     <% if post_impression.user == current_user %>
     <%= link_to '削除', impression_post_impression_path(post_impression.impression,post_impression ),method: :delete, data: { confirm: '本当にいいですか?' } %>
     <% end %>
    </div>
    <% end %>
    <%= paginate @post_impressions %>
  </div>

   </div>
</div>
</div>