config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resources :favorites, only: [:index ,:create, :destroy]
    get "follow_list" => "users#follow_list"
    get "follower_list" => "users#follower_list"
  end
  resources :relationships, only: [:create, :destroy]
  resources :impressions, only: [:index, :show, :create, :destroy] do
    resources :post_impressions, only: [:create, :destroy]
  end
  get "search_content" => "impressions#search_content"
  get "search" => "searches#search"
  post 'favorite/:id' => 'favorites#create', as: 'create_favorite'
  delete 'favorite/:id' => 'favorites#destroy',as: 'destroy_favorite'
  root to: 'impressions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :impression
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @user = User.find(params[:user_id])
    @favorites = @user.favorites.page(params[:page]).per(5)
  end
  def create
    @impression = Impression.find(params[:id])
    Favorite.create(user_id: current_user.id,impression_id: params[:id])
  end
  def destroy
    @impression = Impression.find(params[:id])
    Favorite.find_by(user_id: current_user.id,impression_id: params[:id]).destroy

  end
  private
   def favorite_params
     params.require(:favorite).permit(:user_id,:impression_id)
   end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
      <% if user_signed_in? && current_user.favd?(impression.id) %>
          <td>
            <%= link_to destroy_favorite_path(impression.id), method: :DELETE, remote: true do %>
              <i class = 'good-icon-heartnull'><%= image_tag 'heartfull.png', :size=>'30x25' %></i>
            <% end %>
            <a><%= impression.favorites.count %></a>
          </td>
      <% else %>
          <td>
             <%= link_to create_favorite_path(impression.id), method: :POST, remote: true do %>
               <i class = 'good-icon-heartfull'><%= image_tag 'heartnull.png', :size=>'30x25' %></i>
             <% end %>
             <%= impression.favorites.count %>
          </td>
      <% end %>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @impression.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {impression: @impression}) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @impression.id %>').html("<%= j(render "favorites/favorite", impression: @impression) %>");

app/views/favorites/index.html.erb
<%= flash[:alert] %>
<%= flash[:success] %>
<div class = 'body'>
 <div class = 'user-page-prof'>
  <div>
   <%= attachment_image_tag @user, :image , fallback: "no-image.png", :size => '90x75' %>
  </div>
  <div class = 'user-page-prof-name'>
   <%= @user.name %>
  </div>
  <div>
   <%= @user.introduction %>
  </div>
  <div>
   <%= link_to 'フォローリスト' ,user_follow_list_path(user_id: @user) %><br>
   <%= link_to 'フォロワーリスト' ,user_follower_list_path(user_id: @user) %><br>
   <%= link_to 'いいね!リスト' , user_favorites_path(user_id: @user) %>
  </div>
  <div>
  <% if user_signed_in? %>
   <% if @user.id == current_user.id %>
      <%= link_to "プロフィール編集", edit_user_path(current_user.id) %>
   <% else %>
      <tbody>
       <%= render 'users/follow', user: @user %>
      </tbody>
   <% end %>
  <% else %>
  <% end %>
  </div>
 </div>

<% if user_signed_in? %>
 <div class = 'impression-body'>
   <% @favorites.each do |favorite| %>
    <div class = 'impression-list'>
     <div class = "impression-list-head">
      <div class ="impression-list-icon">
       <%= attachment_image_tag favorite.impression.user, :image , fallback: "no-image.png", :size => '60x50' %>
      </div>
      <div class ="impression-list-body-name">
       <%= link_to favorite.impression.user.name, user_path(favorite.impression.user_id) %><br>
      </div>
      <div id="favorite_buttons_<%= favorite.impression.id %>">
        <%= render "favorites/favorite",impression: favorite.impression %>
      </div>
     </div>
     <div class ="impression-list-body">
      <%= favorite.impression.body %><br>
      <%= favorite.impression.created_at.strftime('%Y/%m/%d') %><br>
      <% favorite.impression.contents.each do |content| %>
       <%= link_to content.name, search_content_path(content_id: content.id) %>
      <% end %><br>

     </div>
     <div class = "impression-list-link">
       <%= link_to 'コメント一覧へ',impression_path(favorite.impression) %><a>(<%= favorite.impression.post_impressions.count %>)</a>
       <% if current_user.id == favorite.impression.user_id %>
        <%= link_to '削除', impression_path(favorite.impression),method: :delete, data: { confirm: '本当にいいですか?' } %>
       <% end %>
     </div>
    </div>
    <% end %>
 <% else %>
    <div class = 'impression-body'>
     <% @favorites.each do |favorite| %>
    <div class = 'impression-list'>
     <div class = "impression-list-head">
      <div class ="impression-list-icon">
       <%= attachment_image_tag favorite.impression.user, :image , fallback: "no-image.png", :size => '60x50' %>
      </div>
      <div class ="impression-list-body-name">
       <%= link_to favorite.impression.user.name, user_path(favorite.impression.user_id) %><br>
      </div>
     </div>
     <div class ="impression-list-body">
      <%= link_to favorite.impression.body, impression_path(favorite.impression) %><br>
      <%= favorite.impression.created_at.strftime('%Y/%m/%d') %><br>
      <% favorite.impression.contents.each do |content| %>
       <%= link_to content.name, search_content_path(content_id: content.id) %>
      <% end %><br>
     </div>
      <div class = "impression-list-link">
       <%= link_to 'コメント一覧へ',impression_path(favorite.impression) %><a>(<%= favorite.impression.post_impressions.count %>)</a>
      </div>

     <% end %>
    </div>


 <% end %>
<%= paginate @favorites %>
     </div>
   </div>
  </div>
 </div>